branch-defaults:
  main:
    environment: my-environment
    group_suffix: null
environment-defaults:
  groweasy-env:
    branch: null
    repository: null
  my-environment:
    branch: null
    repository: null
global:
  application_name: groweasy-analytics
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.9
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
